   


server:
  port: 9191
spring:
  application:
    name: api-gateway
  cloud:
    gateway:        
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flight/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
 
