server:
  port: 8082
spring:
  application:
    name: flight-service
  datasource:
    password: root1234
    url: jdbc:mysql://localhost:3306/flightDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        formate-sql: true
    show-sql: true
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /flight/api-docs
  swagger-ui:
    path: /flight/swagger-ui
